# Generated by Django 6.0 on 2026-01-28 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carrinho_app', '0005_alter_quantidade_item_carrinho_carrinho_and_more'),
        ('hertz_app', '0004_alter_produto_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmacao_Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pagamento', models.CharField(choices=[('pix', 'PIX'), ('cartao_de_credito', 'Cartão de Crédito'), ('cartao_de_debito', 'Cartão de Débito')])),
                ('data_compra', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('em_andamento', 'Em Andamento'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')])),
                ('carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrinho_app.carrinho_compras')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_compras', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item_Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_comprada', models.PositiveIntegerField()),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='confirmar_compra_app.confirmacao_compra')),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hertz_app.produto')),
            ],
        ),
    ]
