# Generated by Django 6.0 on 2026-01-30 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confirmar_compra_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmacao_compra',
            name='status',
        ),
    ]
