# Generated by Django 6.0 on 2026-02-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confirmar_compra_app', '0002_remove_confirmacao_compra_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmacao_compra',
            name='status',
            field=models.CharField(choices=[('em_andamento', 'Em Andamento'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='finalizada'),
        ),
    ]
