# Generated by Django 6.0 on 2025-12-29 02:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('preco', models.IntegerField()),
                ('quantidade_estoque', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_avaliacao', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hertz_app.produto')),
            ],
        ),
    ]
