# Generated by Django 6.0 on 2026-01-10 15:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hertz_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='comentario_avaliacao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(blank=True, choices=[('Fone de Ouvido', 'Fone de Ouvido'), ('Caixa de Som', 'Caixa de Som'), ('Microfone', 'Microfone'), ('Mesa de Som (Mixer)', 'Mesa de Som (Mixer)')], max_length=200),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(default='padrao.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='nota_avaliacao',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao', to='hertz_app.produto'),
        ),
    ]
