# Generated by Django 6.0 on 2026-01-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hertz_app', '0003_avaliacao_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(blank=True, choices=[('fone_de_ouvido', 'Fone de Ouvido'), ('caixa_de_som', 'Caixa de Som'), ('microfone', 'Microfone'), ('mesa_de_Som_(mixer)', 'Mesa de Som (Mixer)')], max_length=200),
        ),
    ]
