# Generated by Django 6.0 on 2026-02-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hertz_app', '0004_alter_produto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem_carrossel_dois',
            field=models.ImageField(default='padrao.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem_carrossel_um',
            field=models.ImageField(default='padrao.png', upload_to=''),
        ),
    ]
