# Generated by Django 6.0 on 2026-01-21 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho_compras',
            name='total',
        ),
    ]
