# Generated by Django 6.0 on 2026-01-24 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho_app', '0003_alter_carrinho_compras_usuario'),
        ('hertz_app', '0003_avaliacao_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho_compras',
            name='itens',
        ),
        migrations.CreateModel(
            name='Quantidade_Item_Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantidade_por_produto', to='carrinho_app.carrinho_compras')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hertz_app.produto')),
            ],
        ),
    ]
