# Generated by Django 6.0 on 2026-01-24 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho_app', '0004_remove_carrinho_compras_itens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantidade_item_carrinho',
            name='carrinho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='carrinho_app.carrinho_compras'),
        ),
        migrations.AlterField(
            model_name='quantidade_item_carrinho',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
